[DISPLAY]
EMBED_TAB_NAME = ATC
EMBED_TAB_COMMAND = qtvcp atc
EMBED_TAB_LOCATION = stackedWidget_mainTab

[EMCIO]
#TOOL_TABLE = tool.tbl
DB_PROGRAM = ./python/tool_db_daemon.py ./tool.db
RANDOM_TOOL_CHANGER = 0
